server:
  port: 9800
spring:
  datasource:
    #    url: jdbc:postgresql://192.168.99.101:5433/postgres #win10
    url: jdbc:postgresql://localhost:5433/postgres #macos
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true